language: cpp
sudo: required
dist: trusty
os:
  - linux
compiler:
  - gcc
  - clang
env:
  global:
    # Legion flags
    # - WARN_AS_ERROR=1
    - REALM_SYNTHETIC_CORE_MAP=""
    - REALM_BACKTRACE=1
    - CC_FLAGS="-Wno-unused-command-line-argument"
cache: ccache
before_install:
  - |
    if [[ "$(uname)" = "Linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo apt-get update -qq
      sudo apt-get install -qq g++-5 mpich2 libmpich-dev
      sudo apt-get install -qq realpath
    fi
  - echo $PWD
  - echo $(realpath $PWD)
  - ls -l /usr/lib/cache
  - if [[ "$(uname)" = "Linux" && "$CXX" = "g++" ]]; then export CXX="g++-5" CC="gcc-5"; fi
install:
  - export CCACHE_BASEDIR=$PWD
  - export CCACHE_LOGFILE=/tmp/cache.debug
  - ./get_deps.sh
script:
  - ccache --zero-stats
  - ./build_all.sh
  - ./test_all.sh
  - ccache --show-stats
  - cat $CCACHE_LOGFILE
