language: cpp
sudo: required
dist: trusty
os:
  - linux
compiler:
  - gcc
  - clang
env:
  global:
    # Legion flags
    - WARN_AS_ERROR=1
    - REALM_SYNTHETIC_CORE_MAP=""
    - REALM_BACKTRACE=1
install:
  - ./get_deps.sh
script:
  - ./build_all.sh
