language: cpp
sudo: required
dist: trusty
os:
  - linux
compiler:
  - gcc
  - clang
env:
  global:
    # Legion flags
    - WARN_AS_ERROR=1
    - REALM_SYNTHETIC_CORE_MAP=""
    - REALM_BACKTRACE=1
    - CC_FLAGS="-Wno-unused-command-line-argument"
before_install:
  # Setup ccache for GCC and Clang.
  - mkdir -p $HOME/bin
  - ln -s /usr/bin/ccache "$HOME/bin/gcc"
  - ln -s /usr/bin/ccache "$HOME/bin/g++"
  - ln -s /usr/bin/ccache "$HOME/bin/clang"
  - ln -s /usr/bin/ccache "$HOME/bin/clang++"
  - export PATH="$HOME/bin${PATH:+:}${PATH}"
  - which g++
  - which clang++
install:
  - ./get_deps.sh
script:
  - ./build_all.sh
  - ./test_all.sh
cache: ccache
